export const SET_BOOKS_SUCCESS = "SET_BOOKS_SUCCESS";
export const SET_BOOKS_ERROR = "SET_BOOKS_ERROR";
export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION";
export const REMOVE_FROM_COLLECTION = "REMOVE_FROM_COLLECTION";
